## Main steps to prepare data for machine learning algorithms
**Note: data must be in 2-D matrix shape (alrady is, while its loaded as table)**

* 1- <a href='#nullvalues'>Dealing with null Values</a>: The data must be clear from any null values.
* 2- <a href='#numvalues'>Convert all to Numerical Values</a>: The data type must be/convert in/to numerical which uses in arithmatic operations.
* 3- <a href='#scaling'> Data Scaling</a>: The data columns must be/convert in/to a simmilar range.

In [1]:
import numpy as np
import pandas as pd
import os
from scipy import stats

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

C:\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
data_file = data_file = os.path.join('D:', os.path.sep, 'prg',  'Datasets', 'general', 'Sample_Preprocessing.csv')
data_file

'D:\\prg\\Datasets\\general\\Sample_Preprocessing.csv'

In [3]:
df = pd.read_csv(data_file)
df.head()

Country   Age   Salary Purchased
0      India  34.0  92000.0       Yes
1  Sri lanka  22.0  25000.0       Yes
2      China  31.0  74000.0       Yes
3  Sri lanka  29.0      NaN        No
4      China  55.0  98000.0       Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    15 non-null     object 
 1   Age        15 non-null     float64
 2   Salary     15 non-null     float64
 3   Purchased  16 non-null     object 
dtypes: float64(2), object(2)
memory usage: 640.0+ bytes


<div id='nullvalues'></div>

# 1- Dealing with null Values
<ol>
<li><a href="#drop_na">Remove</a> rows with null values.</li> 
<li>Fill null values of data column based on <a href="#st_moment">statistical momentums</a> (Mean/Median/Mode/Trimmed Mean).</li>
     <ul>
         <li>based on normallity of data, <u>mean is the most probabble</u> choice which happens in a set (Columns)</li>
         <li>May affect or corrupt data distribution, especially if null values have enoumous count</li>
         <li>e.g: Kurtosis may increse.</li>
     </ul>
<li>Fill null values of data column with <a href="#fill_random">RANDOM values in data range or column value</a></li>
<li>Fill null values of data column with <a href="#fill_na">fixed value</a> (like 0).</li>
<li>Using <a href="#knn_imputer">KNN Imputer</a></li>
    
</ol>



In [5]:
df.isnull().any()

Country       True
Age           True
Salary        True
Purchased    False
dtype: bool

In [6]:
# Total null values
df.isnull().any().sum()

3

In [7]:
# Show rows which contains null values
df[df.isna().any(axis=1)]

Country   Age   Salary Purchased
3  Sri lanka  29.0      NaN        No
6        NaN  43.0  70000.0       Yes
8      India   NaN  60000.0        No

---------------
<div id='drop_na'></div>

### 1-1 Delete rows with null values:

In [8]:
df.dropna() # inplace=True

Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
7   Sri lanka  28.0  40000.0        No
9       China  51.0  89000.0       Yes
10      India  44.0  78000.0       Yes
11  Sri lanka  21.0  20000.0        No
12      China  25.0  30000.0       Yes
13      India  33.0  45000.0       Yes
14      India  42.0  65000.0       Yes
15  Sri lanka  33.0  22000.0        No

In [9]:
# Show NOT NULL rows
# new_df = df[df.notna().all(axis=1)]
df[df.notna().all(axis=1)]


Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
7   Sri lanka  28.0  40000.0        No
9       China  51.0  89000.0       Yes
10      India  44.0  78000.0       Yes
11  Sri lanka  21.0  20000.0        No
12      China  25.0  30000.0       Yes
13      India  33.0  45000.0       Yes
14      India  42.0  65000.0       Yes
15  Sri lanka  33.0  22000.0        No

---------------
<div id='st_moment'></div>

### 1-2 Fill with statistical momentums:

In [10]:
df[df['Age'].isna()]

Country  Age   Salary Purchased
8   India  NaN  60000.0        No

In [11]:
df['Age'].fillna(int(df['Age'].mean()), inplace=True)

In [12]:
df[df['Salary'].isna()]

Country   Age  Salary Purchased
3  Sri lanka  29.0     NaN        No

In [13]:
df['Salary'].fillna(int(df['Salary'].median()), inplace=True)

In [14]:
df['Country'].fillna(df['Country'].mode(), inplace=True)

---------------
<div id='fill_random'></div>

### 1-3 Fill wih random values:

In [15]:
df['Age'].fillna(np.random.randint(low=df['Age'].min(), high=df['Age'].max()), inplace=False)

0     34.0
1     22.0
2     31.0
3     29.0
4     55.0
5     24.0
6     43.0
7     28.0
8     34.0
9     51.0
10    44.0
11    21.0
12    25.0
13    33.0
14    42.0
15    33.0
Name: Age, dtype: float64

---------------
<div id='fill_na'></div>

### 1-4 Fill with fixed value


In [16]:
df['Salary'].fillna(0)

0     92000.0
1     25000.0
2     74000.0
3     60000.0
4     98000.0
5     30000.0
6     70000.0
7     40000.0
8     60000.0
9     89000.0
10    78000.0
11    20000.0
12    30000.0
13    45000.0
14    65000.0
15    22000.0
Name: Salary, dtype: float64

---------------
<div id='knn_imputer'></div>

### 1-5 Using KNN Imputer

#### Split Independent variables [X], and dependent variable or label [Y]

In [17]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [18]:
# choose age, salary column
X[:, 1:]

array([[34.0, 92000.0],
       [22.0, 25000.0],
       [31.0, 74000.0],
       [29.0, 60000.0],
       [55.0, 98000.0],
       [24.0, 30000.0],
       [43.0, 70000.0],
       [28.0, 40000.0],
       [34.0, 60000.0],
       [51.0, 89000.0],
       [44.0, 78000.0],
       [21.0, 20000.0],
       [25.0, 30000.0],
       [33.0, 45000.0],
       [42.0, 65000.0],
       [33.0, 22000.0]], dtype=object)

In [19]:
from sklearn.impute import SimpleImputer

In [20]:
"""
Separate fit and transform in case of process new data,
to fit(traind) data with training data set
but transform test (new) data based on training set.

strategy= mean/ median/ most_frequent (mode)/ constant.
for string values may use mode or constant

"""


si = SimpleImputer(missing_values=np.nan, strategy='mean')

si.fit(X[:, 1:])

X[:, 1:] = si.transform(X[:, 1:])

In [21]:
X

array([['India', 34.0, 92000.0],
       ['Sri lanka', 22.0, 25000.0],
       ['China', 31.0, 74000.0],
       ['Sri lanka', 29.0, 60000.0],
       ['China', 55.0, 98000.0],
       ['India', 24.0, 30000.0],
       [nan, 43.0, 70000.0],
       ['Sri lanka', 28.0, 40000.0],
       ['India', 34.0, 60000.0],
       ['China', 51.0, 89000.0],
       ['India', 44.0, 78000.0],
       ['Sri lanka', 21.0, 20000.0],
       ['China', 25.0, 30000.0],
       ['India', 33.0, 45000.0],
       ['India', 42.0, 65000.0],
       ['Sri lanka', 33.0, 22000.0]], dtype=object)

In [22]:
si.get_params()

{'add_indicator': False,
 'copy': True,
 'fill_value': None,
 'missing_values': nan,
 'strategy': 'mean',
 'verbose': 0}

**Save Imputer (Model) for furthure use**

In [23]:
import pickle

In [24]:
with open(file='0-1 simple_imputer.imp', mode='wb') as file:
    pickle.dump(si, file)

**Load Imputer (Model) for furthure use**

In [25]:
with open(file='0-1 simple_imputer.imp', mode='rb') as file:
    si_new = pickle.load(file)

In [26]:
si_new

SimpleImputer()

In [27]:
test_data = np.array([['USA', np.nan, 100000]])

In [28]:
# Must pass columns same as fited before 
test_data[:, 1:]

array([['nan', '100000']], dtype='<U32')

In [29]:
si_new.transform(test_data[:, 1:])

array([[3.43125e+01, 1.00000e+05]])

--------------------
<div id='numvalues'></div>

# 2- Convert all data to Numerical 

**All variables must be numeric and gain abbility to map into $\mathbb{R}^{N}$ space, and prticipate in mathematic operations**
<br/><br/>
**NOTE: Numerical data like National id, zip code, or Alocate a number to a catogory is LABELING, and has no numerical value.**

<ol>
    <li>Label Encoder</li>
    <li>One Hot Encoder</li>
    <li>Dummy Variable</li>
    
</ol>


## 2-1 Label Encoding (LE)

* 1- Determine column cardinality (unique values)
* 2- Allocate a label to each distinct value.

<b>
Cons: <br/>
</b>

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
X[:, 0]

array(['India', 'Sri lanka', 'China', 'Sri lanka', 'China', 'India', nan,
       'Sri lanka', 'India', 'China', 'India', 'Sri lanka', 'China',
       'India', 'India', 'Sri lanka'], dtype=object)

In [32]:
label_encoder = LabelEncoder()
label_encoder.fit_transform(X[:, 0])

array([1, 2, 0, 2, 0, 1, 3, 2, 1, 0, 1, 2, 0, 1, 1, 2])

In [33]:
X_le = X
X_le[:, 0] = label_encoder.fit_transform(X_le[:, 0])
X_le

array([[1, 34.0, 92000.0],
       [2, 22.0, 25000.0],
       [0, 31.0, 74000.0],
       [2, 29.0, 60000.0],
       [0, 55.0, 98000.0],
       [1, 24.0, 30000.0],
       [3, 43.0, 70000.0],
       [2, 28.0, 40000.0],
       [1, 34.0, 60000.0],
       [0, 51.0, 89000.0],
       [1, 44.0, 78000.0],
       [2, 21.0, 20000.0],
       [0, 25.0, 30000.0],
       [1, 33.0, 45000.0],
       [1, 42.0, 65000.0],
       [2, 33.0, 22000.0]], dtype=object)

## 2-2 One Hot Encoding (OHE)

* 1- Determine column cardinality (unique values)
* 2- Allocate a label to each distinct value.
* 3- Create an individual column for each unique value
* 4- Allocate values (0 or 1) to new column based on main desired column

<b>
Cons: <br/>

* 1- Increase data dimension (number of columns) if cardinality getting high.
* 2- Sparse Matrix
    
</b>

In [34]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [35]:
# Transformers[('arbitrar name for col', Desired function, Column Index)]
col_transformer = ColumnTransformer(transformers=[('Country', OneHotEncoder(), [0])], remainder='passthrough')


In [36]:
X_ohe = X_le

X_ohe = col_transformer.fit_transform(X_ohe)

X_ohe

array([[0.0, 1.0, 0.0, 0.0, 34.0, 92000.0],
       [0.0, 0.0, 1.0, 0.0, 22.0, 25000.0],
       [1.0, 0.0, 0.0, 0.0, 31.0, 74000.0],
       [0.0, 0.0, 1.0, 0.0, 29.0, 60000.0],
       [1.0, 0.0, 0.0, 0.0, 55.0, 98000.0],
       [0.0, 1.0, 0.0, 0.0, 24.0, 30000.0],
       [0.0, 0.0, 0.0, 1.0, 43.0, 70000.0],
       [0.0, 0.0, 1.0, 0.0, 28.0, 40000.0],
       [0.0, 1.0, 0.0, 0.0, 34.0, 60000.0],
       [1.0, 0.0, 0.0, 0.0, 51.0, 89000.0],
       [0.0, 1.0, 0.0, 0.0, 44.0, 78000.0],
       [0.0, 0.0, 1.0, 0.0, 21.0, 20000.0],
       [1.0, 0.0, 0.0, 0.0, 25.0, 30000.0],
       [0.0, 1.0, 0.0, 0.0, 33.0, 45000.0],
       [0.0, 1.0, 0.0, 0.0, 42.0, 65000.0],
       [0.0, 0.0, 1.0, 0.0, 33.0, 22000.0]], dtype=object)

## 2-3 Dummy Variable

In [37]:
df_dummy = df.copy()
df_dummy

Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0  60000.0        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6         NaN  43.0  70000.0       Yes
7   Sri lanka  28.0  40000.0        No
8       India  34.0  60000.0        No
9       China  51.0  89000.0       Yes
10      India  44.0  78000.0       Yes
11  Sri lanka  21.0  20000.0        No
12      China  25.0  30000.0       Yes
13      India  33.0  45000.0       Yes
14      India  42.0  65000.0       Yes
15  Sri lanka  33.0  22000.0        No

In [38]:
pd.concat([df_dummy,
          pd.get_dummies(df_dummy['Country'], dummy_na=False, drop_first=False)], axis=1)

Country   Age   Salary Purchased  China  India  Sri lanka
0       India  34.0  92000.0       Yes      0      1          0
1   Sri lanka  22.0  25000.0       Yes      0      0          1
2       China  31.0  74000.0       Yes      1      0          0
3   Sri lanka  29.0  60000.0        No      0      0          1
4       China  55.0  98000.0       Yes      1      0          0
5       India  24.0  30000.0        No      0      1          0
6         NaN  43.0  70000.0       Yes      0      0          0
7   Sri lanka  28.0  40000.0        No      0      0          1
8       India  34.0  60000.0        No      0      1          0
9       China  51.0  89000.0       Yes      1      0          0
10      India  44.0  78000.0       Yes      0      1          0
11  Sri lanka  21.0  20000.0        No      0      0          1
12      China  25.0  30000.0       Yes      1      0          0
13      India  33.0  45000.0       Yes      0      1          0
14      India  42.0  65000.0       Yes      0      1          0
15  Sri lanka  33.0  22000.0        No      0      0          1

In [39]:
df_dummy

Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0  60000.0        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6         NaN  43.0  70000.0       Yes
7   Sri lanka  28.0  40000.0        No
8       India  34.0  60000.0        No
9       China  51.0  89000.0       Yes
10      India  44.0  78000.0       Yes
11  Sri lanka  21.0  20000.0        No
12      China  25.0  30000.0       Yes
13      India  33.0  45000.0       Yes
14      India  42.0  65000.0       Yes
15  Sri lanka  33.0  22000.0        No

--------------------
<div id='numvalues'></div>

# 3- Scale all data into Same range

**All variables must get normalize and be in same range**
<br/><br/>

<ol>
    <li>Max Norm</li>
    <li>Min Max (Norm) Scaler</li>
    <li>Standard Scaler (Z-Score)</li>
    
</ol>

## 3-1 Max Norm
$$ \text{Max Norm (x) = }\text{x - Min(column)} $$
$$ -1 \le  \text{Max Norm (x)} \le 1$$

In [40]:
from sklearn.preprocessing import MaxAbsScaler

In [41]:
Age_scaled = df['Age'] / df['Age'].max()
Age_scaled

0     0.618182
1     0.400000
2     0.563636
3     0.527273
4     1.000000
5     0.436364
6     0.781818
7     0.509091
8     0.618182
9     0.927273
10    0.800000
11    0.381818
12    0.454545
13    0.600000
14    0.763636
15    0.600000
Name: Age, dtype: float64

In [42]:
max_scaler = MaxAbsScaler()

In [43]:
max_scaler.fit_transform(df['Age'].values.reshape(-1, 1))

array([[0.61818182],
       [0.4       ],
       [0.56363636],
       [0.52727273],
       [1.        ],
       [0.43636364],
       [0.78181818],
       [0.50909091],
       [0.61818182],
       [0.92727273],
       [0.8       ],
       [0.38181818],
       [0.45454545],
       [0.6       ],
       [0.76363636],
       [0.6       ]])

## 3-2 Min/Max Norm

$$\text{Min Max Norm (x) = }\frac{x - Min(column)}{Max - Min}$$
<br/>
$$0 \le  \text{Min Max Norm (x)} \le 1$$

In [44]:
from sklearn.preprocessing import MinMaxScaler

In [45]:
Age_scaled = (df['Age'] - df['Age'].min()) / (df['Age'].max() - df['Age'].min())
Age_scaled

0     0.382353
1     0.029412
2     0.294118
3     0.235294
4     1.000000
5     0.088235
6     0.647059
7     0.205882
8     0.382353
9     0.882353
10    0.676471
11    0.000000
12    0.117647
13    0.352941
14    0.617647
15    0.352941
Name: Age, dtype: float64

In [46]:
min_max_scaler = MinMaxScaler()

In [47]:
min_max_scaler.fit_transform(df['Age'].values.reshape(-1, 1))

array([[0.38235294],
       [0.02941176],
       [0.29411765],
       [0.23529412],
       [1.        ],
       [0.08823529],
       [0.64705882],
       [0.20588235],
       [0.38235294],
       [0.88235294],
       [0.67647059],
       [0.        ],
       [0.11764706],
       [0.35294118],
       [0.61764706],
       [0.35294118]])

## 3-3 Standard Scaler (Z-Score)
**Note: USE FOR NORMAL DATA**

$$Z = \frac{x - \mu}{\sigma}$$
$$ \mu = Mean$$
$$ \sigma = Standard Deviation$$

<br/>
$$ -3 \le  \text{Min Max Norm (x)} \le 3 $$ 
$$ \text{Based on 3 Sigma rule (Normal Dist)}$$


In [48]:
mean = np.mean(df['Age']) # df['Age'].mean()
print('mean: ', mean)

std =  df['Age'].std()
#np.std(df['Age']) #9.80891654 # # 
print(' std: ', std)

mean:  34.3125
 std:  10.130605444230204


In [49]:
# Calculate Standard deviation manually:
a = (df['Age'].values - df['Age'].mean()) ** 2
np.sqrt(np.sum(a)/len(df))

9.808916543125443

In [50]:
Age_scaled = (df['Age'] - mean) / (std)
Age_scaled

0    -0.030847
1    -1.215377
2    -0.326979
3    -0.524401
4     2.042079
5    -1.017955
6     0.857550
7    -0.623112
8    -0.030847
9     1.647236
10    0.956261
11   -1.314087
12   -0.919244
13   -0.129558
14    0.758839
15   -0.129558
Name: Age, dtype: float64

In [51]:
import statistics

In [52]:
statistics.NormalDist(mean, std).zscore(df['Age'])

0    -0.030847
1    -1.215377
2    -0.326979
3    -0.524401
4     2.042079
5    -1.017955
6     0.857550
7    -0.623112
8    -0.030847
9     1.647236
10    0.956261
11   -1.314087
12   -0.919244
13   -0.129558
14    0.758839
15   -0.129558
Name: Age, dtype: float64

In [53]:
stats.zscore(df['Age'].values.reshape(-1, 1))

array([[-0.03185877],
       [-1.25523547],
       [-0.33770294],
       [-0.54159906],
       [ 2.10905047],
       [-1.05133936],
       [ 0.88567376],
       [-0.64354712],
       [-0.03185877],
       [ 1.70125823],
       [ 0.98762182],
       [-1.35718353],
       [-0.9493913 ],
       [-0.13380683],
       [ 0.7837257 ],
       [-0.13380683]])

In [54]:
from sklearn.preprocessing import StandardScaler

In [55]:
standard_scaler = StandardScaler()

In [56]:
standard_scaler.fit_transform(df['Age'].values.reshape(-1, 1))

array([[-0.03185877],
       [-1.25523547],
       [-0.33770294],
       [-0.54159906],
       [ 2.10905047],
       [-1.05133936],
       [ 0.88567376],
       [-0.64354712],
       [-0.03185877],
       [ 1.70125823],
       [ 0.98762182],
       [-1.35718353],
       [-0.9493913 ],
       [-0.13380683],
       [ 0.7837257 ],
       [-0.13380683]])

In [57]:
# standard_scaler.fit_transform(X)

In [58]:
standard_scaler.mean_

array([34.3125])

In [59]:
standard_scaler.scale_

array([9.80891654])

In [60]:
np.sqrt(standard_scaler.var_)

array([9.80891654])