In [1]:
import numpy as np

In [2]:
# a = np.arange(0,10)
a = np.random.randint(low=0, high=10, size=10)
b = np.random.randint(low=0, high=10, size=10)

print('a: ', a)
print('b: ' ,b)


a:  [0 4 9 4 6 8 7 5 4 6]
b:  [9 4 1 9 8 7 5 3 8 7]


### Return Indices of desired values

**numpy.where(criteria, values or formulas based on conditions met, else values)**

In [3]:
np.where(a > 6)

(array([2, 5, 6], dtype=int64),)

In [4]:
np.where(b > 6)

(array([0, 3, 4, 5, 8, 9], dtype=int64),)

### Return desired values

In [5]:
a[np.where(a > 6)]

array([9, 8, 7])

In [6]:
b[np.where(b > 6)]

array([9, 9, 8, 7, 8, 7])

In [7]:
np.sum(a)

53

In [8]:
np.sum(np.where(a > 6)) # sum indices rather than values

13

In [9]:
np.sum(a[np.where(a > 6)]) # sum values

24

In [10]:
np.sum(a, where=(a > 6))

24

In [39]:
# can use formula instead variable a 
np.where(a > 6 ,a, 0)

array([0, 0, 9, 0, 0, 8, 7, 0, 0, 0])

In [35]:
np.sum(np.where(a > 6 ,a, 0))

24